management:
  endpoints.web:
    base-path: /monitoring
    exposure.include: "*"
  endpoint:
    health:
      show-details: always
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}

logging:
  level:
    org.springframework.security: DEBUG